package hust.adventure.events;

public enum EventType {
    INVENTORY_OPENED,
    INVENTORY_CLOSED,
    PLAYER_DIED,
    ITEM_DROPPED,
    QUEST_UPDATED,
    INVENTORY_CHANGED,
    ENTITY_DIED,
    MAP_TRANSITION,
    PUZZLE_FAILED,
    ITEM_USED,
    ITEM_PICKED_UP,
    PUZZLE_SOLVED,
    EXP_GAINED,
    LEVEL_UP,
    ENTITY_DAMAGED,
    TIME_LIMIT_REACHED,
    PLAY_SFX,
    PLAY_BGM,
    GRADUATION,
    ACADEMIC_SUSPENSION
}
